-- MySQL Script generated by MySQL Workbench
-- 01/18/19 11:01:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema curierat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curierat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curierat` DEFAULT CHARACTER SET latin1 ;
USE `curierat` ;

-- -----------------------------------------------------
-- Table `curierat`.`HUB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`HUB` ;

CREATE TABLE IF NOT EXISTS `curierat`.`HUB` (
  `cod_hub` INT NOT NULL AUTO_INCREMENT,
  `an_infiintare` DATE NULL,
  `locatie` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_hub`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Masini`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Masini` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Masini` (
  `cod_masina` INT(11) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(20) NULL DEFAULT NULL,
  `model` VARCHAR(20) NULL DEFAULT NULL,
  `capacitate` INT(11) NULL DEFAULT NULL,
  `an_asamblare` DATE NULL DEFAULT NULL,
  `cod_hub` INT NOT NULL,
  PRIMARY KEY (`cod_masina`),
  INDEX `fk_Masini_HUB1_idx` (`cod_hub` ASC),
  CONSTRAINT `fk_cod_hub_Masini1`
    FOREIGN KEY (`cod_hub`)
    REFERENCES `curierat`.`HUB` (`cod_hub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `curierat`.`Angajati`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Angajati` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Angajati` (
  `cod_angajat` INT NOT NULL AUTO_INCREMENT,
  `nume` VARCHAR(45) NULL,
  `prenume` VARCHAR(45) NULL,
  `salariu` INT NULL,
  `functie` VARCHAR(45) NULL,
  `cod_hub` INT NOT NULL,
  PRIMARY KEY (`cod_angajat`),
  INDEX `fk_Angajati_HUB1_idx` (`cod_hub` ASC),
  CONSTRAINT `fk_cod_hub_Angajati1`
    FOREIGN KEY (`cod_hub`)
    REFERENCES `curierat`.`HUB` (`cod_hub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`masini-repartizate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`masini-repartizate` ;

CREATE TABLE IF NOT EXISTS `curierat`.`masini-repartizate` (
  `cod_masina` INT(11) NOT NULL,
  `cod_angajat` INT NOT NULL,
  INDEX `fk_masini-repartizate_Masini1_idx` (`cod_masina` ASC),
  INDEX `fk_masini-repartizate_Angajati1_idx` (`cod_angajat` ASC),
  CONSTRAINT `fk_masini-repartizate_Masini1`
    FOREIGN KEY (`cod_masina`)
    REFERENCES `curierat`.`Masini` (`cod_masina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_masini-repartizate_Angajati1`
    FOREIGN KEY (`cod_angajat`)
    REFERENCES `curierat`.`Angajati` (`cod_angajat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Comenzi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Comenzi` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Comenzi` (
  `cod_comanda` INT NOT NULL AUTO_INCREMENT,
  `data_plasare` DATE NULL,
  `adresa_plecare` VARCHAR(45) NULL,
  `adresa_destinatie` VARCHAR(45) NULL,
  `cod_hub` INT NOT NULL,
  PRIMARY KEY (`cod_comanda`),
  INDEX `fk_Comenzi_HUB1_idx` (`cod_hub` ASC),
  CONSTRAINT `fk_Comenzi_HUB1`
    FOREIGN KEY (`cod_hub`)
    REFERENCES `curierat`.`HUB` (`cod_hub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Comenzi-Repartizate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Comenzi-Repartizate` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Comenzi-Repartizate` (
  `cod_angajat` INT NOT NULL,
  `cod_comanda` INT NOT NULL,
  INDEX `fk_Comenzi-Repartizate_Angajati1_idx` (`cod_angajat` ASC),
  INDEX `fk_Comenzi-Repartizate_Comenzi1_idx` (`cod_comanda` ASC),
  CONSTRAINT `fk_Comenzi-Repartizate_Angajati1`
    FOREIGN KEY (`cod_angajat`)
    REFERENCES `curierat`.`Angajati` (`cod_angajat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comenzi-Repartizate_Comenzi1`
    FOREIGN KEY (`cod_comanda`)
    REFERENCES `curierat`.`Comenzi` (`cod_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Colet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Colet` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Colet` (
  `cod_colet` INT NOT NULL AUTO_INCREMENT,
  `dimensiune` VARCHAR(45) NULL,
  `greutate` INT NULL,
  `cod_comanda` INT NOT NULL,
  PRIMARY KEY (`cod_colet`),
  INDEX `fk_Colet_Comenzi1_idx` (`cod_comanda` ASC),
  CONSTRAINT `fk_Colet_Comenzi1`
    FOREIGN KEY (`cod_comanda`)
    REFERENCES `curierat`.`Comenzi` (`cod_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Ruta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Ruta` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Ruta` (
  `cod_ruta` INT NOT NULL AUTO_INCREMENT,
  `loc_comanda` VARCHAR(45) NULL,
  `data` DATE NULL,
  `ora` TIME NULL,
  `cod_angajat` INT NOT NULL,
  `cod_colet` INT NOT NULL,
  PRIMARY KEY (`cod_ruta`),
  INDEX `fk_Ruta_Angajati1_idx` (`cod_angajat` ASC),
  INDEX `fk_Ruta_Colet1_idx` (`cod_colet` ASC),
  CONSTRAINT `fk_Ruta_Angajati1`
    FOREIGN KEY (`cod_angajat`)
    REFERENCES `curierat`.`Angajati` (`cod_angajat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ruta_Colet1`
    FOREIGN KEY (`cod_colet`)
    REFERENCES `curierat`.`Colet` (`cod_colet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Clienti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Clienti` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Clienti` (
  `cod_clienti` INT NOT NULL AUTO_INCREMENT,
  `nume` VARCHAR(45) NULL,
  `prenume` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `adresa` VARCHAR(45) NULL,
  `adresa_mail` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_clienti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Factura` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Factura` (
  `cod_factura` INT NOT NULL AUTO_INCREMENT,
  `total_plata` INT NULL,
  `data_infiintarii` DATE NULL,
  `cod_colet` INT NOT NULL,
  `cod_clienti` INT NOT NULL,
  PRIMARY KEY (`cod_factura`),
  INDEX `fk_Factura_Colet1_idx` (`cod_colet` ASC),
  INDEX `fk_Factura_Clienti1_idx` (`cod_clienti` ASC),
  CONSTRAINT `fk_Factura_Colet1`
    FOREIGN KEY (`cod_colet`)
    REFERENCES `curierat`.`Colet` (`cod_colet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Clienti1`
    FOREIGN KEY (`cod_clienti`)
    REFERENCES `curierat`.`Clienti` (`cod_clienti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Comenzi-Clienti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Comenzi-Clienti` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Comenzi-Clienti` (
  `cod_clienti` INT NOT NULL,
  `cod_comanda` INT NOT NULL,
  INDEX `fk_Comenzi-Clienti_Clienti1_idx` (`cod_clienti` ASC),
  INDEX `fk_Comenzi-Clienti_Comenzi1_idx` (`cod_comanda` ASC),
  CONSTRAINT `fk_Comenzi-Clienti_Clienti1`
    FOREIGN KEY (`cod_clienti`)
    REFERENCES `curierat`.`Clienti` (`cod_clienti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comenzi-Clienti_Comenzi1`
    FOREIGN KEY (`cod_comanda`)
    REFERENCES `curierat`.`Comenzi` (`cod_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curierat`.`Conturi_angajati`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curierat`.`Conturi_angajati` ;

CREATE TABLE IF NOT EXISTS `curierat`.`Conturi_angajati` (
  `cod_cont` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NULL,
  `Parola` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_cont`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
